import { useState, useEffect, useCallback } from 'react'
import Head from 'next/head'
import { fmt, apiFetch } from '../lib/utils'
const S={card:{background:'#fff',borderRadius:16,padding:16,boxShadow:'0 2px 12px rgba(0,0,0,.06)'},darkCard:{background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',borderRadius:16,padding:16},input:{width:'100%',background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,padding:'12px 16px',color:'#fff',fontSize:15,outline:'none',boxSizing:'border-box',marginBottom:14},label:{display:'block',fontSize:11,color:'#4a7fc1',fontWeight:700,letterSpacing:1,textTransform:'uppercase',marginBottom:6},btn:(bg)=>({width:'100%',background:bg,border:'none',borderRadius:12,padding:'13px',color:'#fff',fontWeight:800,fontSize:15,cursor:'pointer',fontFamily:"'Nunito'"}),ghostBtn:{background:'transparent',border:'1px solid rgba(255,255,255,.15)',borderRadius:12,padding:'12px',color:'#888',fontWeight:700,cursor:'pointer',fontFamily:"'Nunito'"}}
function Spinner({small}){const s=small?20:40;return <div style={{width:s,height:s,border:`3px solid rgba(0,114,255,.25)`,borderTop:'3px solid #0072ff',borderRadius:'50%',animation:'spin .7s linear infinite',margin:small?'0':'80px auto'}}/>}
function Toast({msg,type,onClose}){useEffect(()=>{const t=setTimeout(onClose,3000);return()=>clearTimeout(t)},[]);return(<div style={{position:'fixed',bottom:90,left:'50%',transform:'translateX(-50%)',zIndex:999,background:type==='error'?'#c0392b':'#1bc47d',color:'#fff',borderRadius:12,padding:'12px 24px',fontWeight:800,fontSize:14,boxShadow:'0 4px 20px rgba(0,0,0,.4)',whiteSpace:'nowrap'}}>{type==='error'?'✗':'✓'} {msg}</div>)}
function Modal({title,onClose,children}){return(<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.85)',zIndex:200,display:'flex',alignItems:'flex-end',justifyContent:'center'}} onClick={e=>e.target===e.currentTarget&&onClose()}><div style={{background:'#0d1a3a',border:'1px solid rgba(255,255,255,.1)',borderRadius:'24px 24px 0 0',padding:28,width:'100%',maxWidth:500,maxHeight:'90vh',overflowY:'auto'}}><div style={{width:40,height:4,background:'rgba(255,255,255,.15)',borderRadius:2,margin:'0 auto 20px'}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h3 style={{fontWeight:800,fontSize:18}}>{title}</h3><button onClick={onClose} style={{background:'none',border:'none',color:'#888',fontSize:24,cursor:'pointer'}}>×</button></div>{children}</div></div>)}
function StatusBadge({status}){const cfg={pending:{bg:'#fff3cd',color:'#856404',label:'Pendiente'},approved:{bg:'#d1f5e0',color:'#1a7a4a',label:'Aprobado'},rejected:{bg:'#fde8e8',color:'#c0392b',label:'Rechazado'},completed:{bg:'#d1f5e0',color:'#1a7a4a',label:'Completado'}};const c=cfg[status]||cfg.pending;return <span style={{background:c.bg,color:c.color,borderRadius:6,padding:'2px 10px',fontSize:11,fontWeight:800}}>{c.label}</span>}
function Login({onLogin}){const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [err,setErr]=useState('');const [loading,setLoading]=useState(false);const handle=async()=>{if(!email||!pass){setErr('Completa todos los campos');return}setLoading(true);setErr('');try{const d=await apiFetch('/api/login',{method:'POST',body:{email,password:pass}});localStorage.setItem('dopchain_token',d.token);onLogin(d.user)}catch(e){setErr(e.message)}setLoading(false)};return(<div style={{minHeight:'100vh',background:'radial-gradient(ellipse at 50% 0%,rgba(0,114,255,.2) 0%,transparent 60%),#0a0f1e',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:24}}><div style={{textAlign:'center',marginBottom:36}}><div style={{width:80,height:80,borderRadius:24,background:'linear-gradient(135deg,#00c6ff,#0072ff)',display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 16px',fontSize:36,boxShadow:'0 8px 32px rgba(0,114,255,.4)'}}>⛓️</div><h1 style={{fontFamily:"'Bebas Neue'",fontSize:38,letterSpacing:4}}>DOPCHAIN</h1><p style={{color:'#4a7fc1',fontSize:13,marginTop:4}}>Plataforma Financiera · DOP</p></div><div style={{width:'100%',maxWidth:380,...S.darkCard}}><label style={S.label}>Correo electrónico</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="tu@correo.do" style={S.input}/><label style={S.label}>Contraseña</label><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="••••••••" style={S.input} onKeyDown={e=>e.key==='Enter'&&handle()}/>{err&&<p style={{color:'#f87171',fontSize:13,textAlign:'center',marginBottom:12}}>{err}</p>}<button onClick={handle} disabled={loading} style={S.btn('linear-gradient(135deg,#0072ff,#00c6ff)')}>{loading?<span style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8}}><Spinner small/>Ingresando…</span>:'Ingresar →'}</button></div></div>)}export default Dopchain;
function Header({user}){return(<div style={{position:'sticky',top:0,zIndex:50,background:'rgba(10,15,30,.97)',backdropFilter:'blur(16px)',borderBottom:'1px solid rgba(255,255,255,.06)',padding:'13px 16px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{width:30,height:30,borderRadius:9,background:'linear-gradient(135deg,#0072ff,#00c6ff)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:15}}>⛓️</div><span style={{fontFamily:"'Bebas Neue'",fontSize:20,letterSpacing:2}}>DOPCHAIN</span></div><div style={{background:'rgba(0,114,255,.15)',border:'1px solid rgba(0,198,255,.25)',borderRadius:20,padding:'6px 14px',display:'flex',alignItems:'center',gap:6}}><span style={{fontSize:11,color:'#00c6ff'}}>⚡</span><span style={{fontFamily:"'Bebas Neue'",fontSize:16,letterSpacing:1}}>{fmt(user?.balance)}</span></div></div>)}

